# -*- coding: utf-8 -*-
"""Assignment1_Dictionary.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zch2WrGD_fAtedHswAtBEPXZYNu1W8As
"""

Dict = {'name':'pooja','profession':'software','hobby':'sketching'}

newDict = Dict.copy()
print(newDict)

newDict.clear()
print(newDict)

newDict = dict.fromkeys(['abc','xyz','pqr'],2) # requires 2 arguments 1st iterable 2nd value
print(newDict)

Dict.get('name') #returns value of key if key is not in dict returns none

Dict.items() # returns list of tuples of key-value pair

Dict.keys() #returns list of keys

Dict.pop('hobby') # removes given key and returns value, if given key is not in dict returns keyError

newDict.popitem() # remove last key-value pair and returns it in tuple form

Dict.setdefault('hobby','sketching') # if key is present then it replaces with new given value, if key is not present it update the dict with given key-value
print(Dict)

newDict.update({'gift':'book'})
newDict.update(R=90)
print(newDict)

newDict.values() # returns list of values